### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-remotes-HASS#1]
I quickly hacked the tests, but some still need fixing. Request assistance from @azogue

**Comment by azogue** [comment]
Hi Rob, I'll take a look and fix them later today, ok?

From my part, I was already working on the PR for main hue in HA Core. 

I have it working successfully, with just 1 common update listener for all hue sensors (bs/s + remotes), now I'm **trying to implement an OptionsFlow to enable/disable sensors and/or remotes for each bridge**, so there is no breaking change for current users, and it can be enabled from UI

It's looking good :)

<img width="1496" alt="Captura de pantalla 2020-03-14 a las 9 20 06" src="https://user-images.githubusercontent.com/9748301/76678129-ad68fe00-65d5-11ea-8dbb-3aaa84e572a9.png">

**Comment by robmarkcole** [comment]
Looks like great progress!
