### ISSUE TITLE
Question: Will this new repo be added to HACS?

### ISSUE THREAD

**Issue by mikesalz** [robmarkcole/Hue-remotes-HASS#5]
Splitting the sensors and remotes is a good idea.  Will the remotes repo be added to HACS?

**Comment by azogue** [comment]
Yes, that's the idea :)

**Comment by inverse** [comment]
Looking forward :) Thanks for doing this!

**Comment by robmarkcole** [comment]
Tracking in https://github.com/robmarkcole/Hue-remotes-HASS/issues/8
